const ErrorCodes = {
  PASSPORT_UNAUTHORIZED_ERROR_CODE: 1,
  INVALID_CREDENTIALS_ERROR_CODE: 2,
  ACCOUNT_LOCKED_ERROR_CODE: 3,
  INVALID_NEW_PASSWORD_ERROR_CODE: 4,
  USER_NOT_FOUND_ERROR_CODE: 5,
  DUPLICATED_USER_ERROR_CODE: 6,
  UPDATE_REQUIRED_ERROR_CODE: 44,
  RYT_ERROR_CODE: 55,
  INSUFFICIENT_PERMISSION_ERROR_CODE: 66,
  INPUT_VALIDATION_ERROR_CODE: 77,
  MALFORMED_JSON_ERROR_CODE: 88,
  RUNTIME_ERROR_CODE: 99
};

export default ErrorCodes;
